AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::586369390114:role/service-role/search-photos-role-tu4ve7f4'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET
        Api2:
          Type: Api
          Properties:
            Path: /search
            Method: GET
        Api3:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./index-photos
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::586369390114:role/service-role/index-photos-role-z00lemnp'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
  Bucket1:
    Type: 'AWS::S3::Bucket'
