AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  PhotosApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Alpha
      DefinitionUri: ./swagger.yaml
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      FunctionName: searchphotos
      CodeUri: ./search-photos
      Description: ''
      MemorySize: 128
      Timeout: 3
      # Role: 'arn:aws:iam::586369390114:role/service-role/search-photos-role-tu4ve7f4'
      Policies:
        - AmazonLexFullAccess
      Events:
        PhotoApi:
          Type: Api
          Properties:
            RestApiId: !Ref "PhotosApiGateway"
            Path: /search
            Method: GET

  indexphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: indexphotos
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./index-photos
      Description: ''
      MemorySize: 128
      Timeout: 3
      # Role: 'arn:aws:iam::586369390114:role/service-role/index-photos-role-z00lemnp'
      Policies:
        - AmazonS3FullAccess
        - AmazonLexFullAccess
        - AmazonRekognitionFullAccess
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket: !Ref photosBucket2
            Events: s3:ObjectCreated:*
  photosBucket2:
    Type: AWS::S3::Bucket
